recipes-devtools/python/python3-pycuda_2020.1.bb
recipes-devtools/python/python3-pytools_2020.1.bb

Add recipe for installing pycuda python module.
Signed-off-by: Marek Belisko marek.belisko@open-nandra.com

pycuda: add recipe

---

recipes-test/tegra-tests/tensorrt-tests/run-tensorrt-tests.sh
recipes-test/tegra-tests/tensorrt-tests_1.0.bb

to automating test runs of the TensorRT samples.

tegra-tests: add tensorrt-tests recipe

---

recipes-test/tegra-tests/tensorrt-tests_1.0.bb

tensorrt-tests: fix override syntax and add tar in RDEPENDS list

---

recipes-devtools/vpi/vpi1-samples_1.1.12.bb

vpi1-samples: update to 1.1.12

---

recipes-devtools/deepstream/deepstream-6.0_6.0.0-1.bb

Migrating this recipe from meta-tegra.

deepstream-6.0: add recipe

---

recipes-devtools/deepstream/deepstream-6.0-pyds/0001-Fixes-for-cross-building.patch
recipes-devtools/deepstream/deepstream-6.0-pyds/0002-Allow-apps-to-be-run-from-other-working-directories.patch
recipes-devtools/deepstream/deepstream-6.0-pyds_1.1.0.bb

Got this building in dunfell.  Tests should be added so we can verify that the bindings actually work, so don't merge this yet.

deepstream-6.0 python bindings

---

recipes-devtools/vpi/vpi1-samples_1.2.3.bb

vpi1-samples: update to 1.2.3

---

recipes-devtools/cnmem/cnmem_v1.0.0.bb

NVIDIA CNMeM is a simple memory manager library for CUDA.
This recipe is a dependency for NVIDIA Triton.

cnmem: new recipe

---

recipes-support/libb64/libb64/0001-example-Do-not-run-the-tests.patch
recipes-support/libb64/libb64/0002-use-BUFSIZ-as-buffer-size.patch
recipes-support/libb64/libb64/0003-fix-integer-overflows.patch
recipes-support/libb64/libb64/0004-Fix-off-by-one-error.patch
recipes-support/libb64/libb64/0005-make-overriding-CFLAGS-possible.patch
recipes-support/libb64/libb64/0006-do-not-export-the-CHARS_PER_LINE-variable.patch
recipes-support/libb64/libb64/0007-initialize-encoder-decoder-state-in-the-constructors.patch
recipes-support/libb64/libb64_1.2.1.bb

libb64: new recipe (meta-oe backport)

---

recipes-support/re2/re2_2020.11.01.bb

re2: new recipe (meta-oe backport)

---

recipes-devtools/vpi/vpi2-samples_2.1.6.bb

vpi2-samples: update to 2.1.6

---

recipes-devtools/python/python3-jetson-stats_3.1.2.bb

Jetson stats build fix

---

recipes-devtools/triton/triton-common/0001-fix-cmake-build.patch

Fix build issue on triton-common on master branch

triton-common: fix build issue

---

recipes-devtools/dlpack/dlpack_0.7.bb
recipes-devtools/python/python3-geventhttpclient_2.0.8.bb
recipes-devtools/python/python3-rapidjson_1.9.bb
recipes-devtools/triton/triton-client/0001-fix-cmake-build.patch
recipes-devtools/triton/triton-client_r22.05.bb
recipes-devtools/triton/triton-python-backend/0001-fix-cmake-build.patch
recipes-devtools/triton/triton-python-backend_r22.05.bb

This PR generates python bindings for the triton-client library

triton-client: add triton-client http bindings for python

---

recipes-devtools/triton/triton-backend/0001-Build-fixups.patch
recipes-devtools/triton/triton-backend_2.22.0.bb
recipes-devtools/triton/triton-client/0001-Build-fixups.patch
recipes-devtools/triton/triton-client_2.22.0.bb
recipes-devtools/triton/triton-common/0001-Build-fixups.patch
recipes-devtools/triton/triton-common_2.22.0.bb
recipes-devtools/triton/triton-core/0001-Build-fixups.patch
recipes-devtools/triton/triton-core_2.22.0.bb
recipes-devtools/triton/triton-python-backend_2.22.0.bb
recipes-devtools/triton/triton-server/0001-Build-fixups.patch
recipes-devtools/triton/triton-server_2.22.0.bb
recipes-devtools/triton/triton-tensorrt-backend/0001-Build-fixups.patch
recipes-devtools/triton/triton-tensorrt-backend_2.22.0.bb

- fix build issues
- move from version r22.05 to 2.22.0 (r22.05 is container version)
- introduce improvements

triton-*: update recipes

---

recipes-devtools/vpi/vpi2-samples/CMakeLists.txt

vpi2-samples: add image view sample application

---

recipes-test/tegra-tests/vpi2-tests/run-vpi2-tests.sh

vpi2-tests: update vpi2 test script and add image view sample

---

recipes-devtools/vpi/vpi2-samples/CMakeLists.txt
recipes-devtools/vpi/vpi2-samples_2.2.4.bb
recipes-test/tegra-tests/vpi2-tests/run-vpi2-tests.sh

* This PR is depending on [#1162](https://github.com/OE4T/meta-tegra/pull/1162)

VPI2 updates

---

recipes-devtools/vpi/vpi2-samples_2.2.6.bb
recipes-test/tegra-tests/vpi2-tests/run-vpi2-tests.sh

Updates the vpi2-samples and vpi2-tests recipes.

Update for JetPack 5.1.1/L4T R35.3.1

---

recipes-devtools/cnmem/cnmem_v1.0.0.bb
recipes-devtools/dlpack/dlpack_0.7.bb
recipes-devtools/libevhtp/libevhtp/0001-fix-cmake-build.patch
recipes-devtools/libevhtp/libevhtp_1.2.18.bb
recipes-devtools/python/python3-geventhttpclient_2.0.8.bb
recipes-devtools/python/python3-rapidjson_1.9.bb
recipes-devtools/triton/triton-backend/0001-Build-fixups.patch
recipes-devtools/triton/triton-backend_2.22.0.bb
recipes-devtools/triton/triton-client/0001-Build-fixups.patch
recipes-devtools/triton/triton-client_2.22.0.bb
recipes-devtools/triton/triton-common/0001-Build-fixups.patch
recipes-devtools/triton/triton-common_2.22.0.bb
recipes-devtools/triton/triton-core/0001-Build-fixups.patch
recipes-devtools/triton/triton-core_2.22.0.bb
recipes-devtools/triton/triton-python-backend/0001-fix-cmake-build.patch
recipes-devtools/triton/triton-python-backend_2.22.0.bb
recipes-devtools/triton/triton-server/0001-Build-fixups.patch
recipes-devtools/triton/triton-server_2.22.0.bb
recipes-devtools/triton/triton-tensorrt-backend/0001-Build-fixups.patch
recipes-devtools/triton/triton-tensorrt-backend_2.22.0.bb

Backport Triton and relevant dependencies from `kirkstone` to `kirkstone-l4t-r32.7.x` branch

triton: backport from kirkstone

---

recipes-devtools/python/python3-jetson-stats/0001-fix-installation-process-issue-and-cleanup.patch
recipes-devtools/python/python3-jetson-stats/0002-fix-paths-to-match-with-OE-and-getting-the-right-ver.patch

```
root@jetson-xavier-nx-devkit-emmc:~# python3 -m jtop.core.jetson_libraries                                                                                                                                   
CUDA: 11.4
OPENCV: not Installed!
TensorRT: 8.5.2
cuDNN: 8.6.0
VPI: 2.2.6
Vulkan: 1.3.250
root@jetson-xavier-nx-devkit-emmc:~# systemctl status jtop                                                                                                                                                  
* jtop.service - jtop service
Loaded: loaded (8;;file://jetson-xavier-nx-devkit-emmc/usr/lib/systemd/system/jtop.service/usr/lib/systemd/system/jtop.service8;;; enabled; preset: enabled)8;;
Active: active (running) since Sun 2023-08-27 13:52:15 UTC; 26min ago
Main PID: 978 (python3)
Tasks: 7 …
```

python3-jetson-stats: refresh patches

---

recipes-devtools/python/python3-jetson-stats/0001-fix-installation-process-issue-and-cleanup.patch
recipes-devtools/python/python3-jetson-stats/0002-fix-paths-to-match-with-OE-and-getting-the-right-ver.patch
recipes-devtools/python/python3-jetson-stats_4.2.3.bb

to monitor jetson resources
* Tests were done on machine `jetson-nano-devkit-emmc` with `demo-image-full` image 
* Add the following line into `conf/local.conf`
```
CORE_IMAGE_BASE_INSTALL_append = " python3-jetson-stats"
```
* Result
```
root@jetson-tx2-devkit:~# hostnamectl 
Static hostname: jetson-tx2-devkit
Icon name: computer
Machine ID: 78f4ec878edc4b61a51ad66504c8a0c2
Boot ID: bf47379c14d14f78a8c0577e4af08583
Operating System: OE4Tegra Demonstration Distro 3.1.27+snapshot-20230827 (dunfell-l4t-r32.7)
Kernel: Linux 4.9.337-l4t-r32.7.4+ga1cf17bc0aa0
Architecture: arm64
root@jetson-tx2-devkit:~# 
root@jetson-tx2-devkit:~# systemctl status jtop 
● jtop.service - jtop service
Loaded: loaded (/lib/systemd/system/jtop.service; enabled; vendor preset: enabled)
Active: active (running) …
```

python3-jetson-stats: add recipe

---

recipes-devtools/deepstream/deepstream-7.0-pyds/0002-Allow-apps-to-be-run-from-other-working-directories.patch
recipes-devtools/libevhtp/libevhtp/0001-fix-cmake-build.patch
recipes-devtools/python/python3-jetson-stats/0001-fix-installation-process-issue-and-cleanup.patch
recipes-devtools/python/python3-jetson-stats/0002-fix-paths-to-match-with-OE-and-getting-the-right-ver.patch
recipes-devtools/python/python3-pycuda/0001-add-nvcc-flag-allow-unsupported-compiler-to-allow-cu.patch
recipes-devtools/triton/triton-backend/0001-Build-fixups.patch
recipes-devtools/triton/triton-client/0001-Build-fixups.patch
recipes-devtools/triton/triton-common/0001-Build-fixups.patch
recipes-devtools/triton/triton-core/0001-Build-fixups.patch
recipes-devtools/triton/triton-python-backend/0001-fix-cmake-build.patch
recipes-devtools/triton/triton-server/0001-Build-fixups.patch
recipes-devtools/triton/triton-tensorrt-backend/0001-Build-fixups.patch
recipes-devtools/triton/triton-tensorrt-backend/0002-add-support-for-kUINT8.patch
recipes-test/eglstreams/eglstreams-kms-example/cross-build.patch
recipes-test/tegra-tests/nvidia-docker-tests/0001-Distro-agnostic-support-for-Test-ML-script.patch
recipes-test/tegra-tests/nvidia-docker-tests/0002-Add-version-remap-script-support.patch

This is turning into build QA error in poky master

recipes: Add missing Upstream-Status tags

---

recipes-devtools/python/python3-jetson-stats/0001-fix-installation-process-issue-and-cleanup.patch
recipes-devtools/python/python3-jetson-stats/0002-fix-paths-to-match-with-OE-and-getting-the-right-ver.patch
recipes-devtools/python/python3-jetson-stats_4.2.4.bb

python3-jetson-stats: update to 4.2.4

---

recipes-devtools/python/python3-jetson-stats/0001-fix-installation-process-issue-and-cleanup.patch
recipes-devtools/python/python3-jetson-stats/0002-fix-paths-to-match-with-OE-and-getting-the-right-ver.patch
recipes-devtools/python/python3-jetson-stats_4.3.1.bb

python3-jetson-stats: upgrade 4.2.12 -> 4.3.1
