OE4T/meta-tegra-community

recipes-devtools/deepstream/deepstream-tlt-apps/0001-Cross-build-fixups.patch
recipes-devtools/deepstream/deepstream-tlt-apps_3.0.bb

This PR adds a recipe that builds several deepstream tlt sample apps as well as the libnvds_infercustomparser_tlt.so custom parser library from NVIDIA's [deepstream_tao_apps](https://github.com/NVIDIA-AI-IOT/deepstream_tao_apps) repository.
I separated the samples and custom parser into separate packages so that the custom parser can be built by itself if desired.
I'm targeting the dunfell-l4t-r32.4.3 branch since that's what my image is based on, but I can also open another PR targeting the master branch once this one gets approved.

deepstream-tlt-apps: add recipe

---

recipes-multimedia/gstreamer/gstreamer1.0-plugins-bad_%.bbappend

Modifying PACKAGECONFIG via anonymous python doesn't work
when the function is executed after the anonymous python
functions in base.bbclass, so rework the changes to append
or modify variables instead.
Signed-off-by: Matt Madison <matt@madison.systems>

gstreamer-plugins-bad: rework PACKAGECONFIG setting

---

recipes-connectivity/openssl/files/environment.d-openssl.sh
recipes-connectivity/openssl/openssl111/0001-buildinfo-strip-sysroot-and-debug-prefix-map-from-co.patch
recipes-connectivity/openssl/openssl111/0001-skip-test_symbol_presence.patch
recipes-connectivity/openssl/openssl111/afalg.patch
recipes-connectivity/openssl/openssl111/reproducible.patch
recipes-connectivity/openssl/openssl111/run-ptest
recipes-connectivity/openssl/openssl111_1.1.1l.bb
recipes-devtools/deepstream/deepstream-6.0_6.0.0-1.bb

* Imports a recipe for openssl 1.1.1 to allow it to co-reside with openssl 3, to satisfy the runtime dependencies for the DS-6.0 prebuilt libraries
* Recipe for DS-6.0 excludes features with other dependencies that we do not have recipes for via PACKAGECONFIG settings.

Deepstream-6.0 recipe for master

---

recipes-devtools/python/python3-jetson-stats/0001-jtop-fix-no-attribute-issue.patch
recipes-devtools/python/python3-jetson-stats_3.1.2.bb

This adds a recipe for the jetson-stats tool. It makes it somewhat easier to monitor resource usage than with tegrastats.

python3-jetson-stats: new recipe

---

recipes-devtools/libevhtp/libevhtp/0001-fix-cmake-build.patch
recipes-devtools/libevhtp/libevhtp_1.2.18.bb

libevhtp is an embedded HTTP server library.
This recipe is a dependency for NVIDIA Triton.
Signed-off-by: Roger Knecht <roger@norberthealth.com>

libevhtp: new recipe

---

recipes-devtools/cnmem/cnmem_v1.0.0.bb

NVIDIA CNMeM is a simple memory manager library for CUDA.
This recipe is a dependency for NVIDIA Triton.
Signed-off-by: Roger Knecht <roger@norberthealth.com>

cnmem: new recipe

---

recipes-devtools/python/python3-jepture/0001-setup.py-don-t-hardcode-paths.patch
recipes-devtools/python/python3-jepture/0002-v4l2-remove-duplicate-symbols-from-nvidia-extensions.patch
recipes-devtools/python/python3-jepture/0003-Revert-argus_stream-update-certain-symbols-to-work-w.patch
recipes-devtools/python/python3-jepture_git.bb

I've had a lot of trouble getting camera capture to work correctly with nvargus. The problem is that the daemon continuously captures frames and if you consume them using the gstreamer module, you can't set the daemon's framerate and you need to consume them at the same rate as the server captures them. I found this python module called jepture that captures frames directly without going through the gstreamer plugin. This PR adds a recipe for it.

python3-jepture: new package

---

recipes-test/tegra-tests/nvidia-docker-tests/0001-Distro-agnostic-support-for-Test-ML-script.patch
recipes-test/tegra-tests/nvidia-docker-tests/run-docker-tests.sh.in
recipes-test/tegra-tests/nvidia-docker-tests_1.0.bb

- This will test container compatibility on the device image
- Tested on `jetson-xavier-nx-devkit-emmc`

tegra-tests: add nvidia-docker-tests

---

recipes-devtools/dlpack/dlpack_0.7.bb
recipes-devtools/python/python3-geventhttpclient_2.0.8.bb
recipes-devtools/python/python3-rapidjson_1.9.bb
recipes-devtools/triton/triton-client/0001-fix-cmake-build.patch
recipes-devtools/triton/triton-client_r22.05.bb
recipes-devtools/triton/triton-python-backend/0001-fix-cmake-build.patch
recipes-devtools/triton/triton-python-backend_r22.05.bb

@ichergui Here is the master PR for the triton-client python bindings.
The changes are the same as in the `dunfell` branch except:
- the obvious adjustments for the new recipe syntax
- fixes for compiler issues in the `triton-python-backend` which were not present in `dunfell`.

triton-client: add triton-client http bindings for python

---

recipes-devtools/python/python3-pycuda_2020.1.bb

On kirkstone branch following is reported:
DEBUG: Python function extend_recipe_sysroot finished | DEBUG: Executing shell function do_configure
| cp: '/home/ubuntu/yocto/my-test-os/build/tmp/work/armv8a_tegra194-poky-linux/python3-pycuda/2020.1-r0/pycuda-2020.1/siteconf.py' and '/home/ubuntu/yocto/my-test-os/build/tmp/work/armv8a_tegra194-poky-linux/python3-pycuda/2020.1-r0/pycuda-2020.1/siteconf.py' are the same file
Fix it by remove redundant copy.
Signed-off-by: Marek Belisko <marek.belisko@open-nandra.com>

recipes-devtools: python3-pycuda: Fix configure issue

---

recipes-test/tegra-tests/nvidia-docker-tests/0002-Add-version-remap-script-support.patch
recipes-test/tegra-tests/nvidia-docker-tests/l4t_version_remap.sh.in
recipes-test/tegra-tests/nvidia-docker-tests_1.0.bb

* Add support for an l4t_version_remap script which can
remap the L4T_VERSION environment variable to match containers
which actually exist in NGC.
* Go to latest upstream
* Fix some space/tab inconsistencies in the recipe.
* Add necessary test scripts to the rootfs

nvidia-docker-tests: Add support for r35.2.1

---

recipes-devtools/deepstream/deepstream-6.2-pyds/0001-Fixes-for-cross-building.patch
recipes-devtools/deepstream/deepstream-6.2-pyds/0002-Allow-apps-to-be-run-from-other-working-directories.patch
recipes-devtools/deepstream/deepstream-6.2-pyds_1.1.6.bb
recipes-devtools/deepstream/deepstream-6.2_6.2.0-1.bb
recipes-test/tegra-tests/deepstream-tests/run-deepstream-tests.sh
recipes-test/tegra-tests/deepstream-tests_1.0.bb

* Tests were done by using `demo-image-full` image with `Jetson Xavier AGX` machine
*  add `deepstream-tests` recipe to your image
* After flashing , and device booting properly, run the script `run-deepstream-tests`
* Result
```
nvstreammux: Successfully handled EOS for source_id=0
Frame Number= 1437 Number of Objects= 14 Vehicle_count= 11 Person_count= 3
Frame Number= 1437 Number of Objects= 15 Vehicle_count= 13 Person_count= 2
Frame Number= 1438 Number of Objects= 16 Vehicle_count= 13 Person_count= 3
Frame Number= 1438 Number of Objects= 15 Vehicle_count= 12 Person_count= 3
Frame Number= 1439 Number of Objects= 14 Vehicle_count= 11 Person_count= 3
Frame Number= 1439 Number of Objects= 14 Vehicle_count= 11 Person_count= 3
Frame Number= 1440 Number of Objects= 13 Vehicle_count= 11 …
```

Updates for deepstream 6.2

---

recipes-test/tegra-tests/nvidia-docker-tests/0001-Distro-agnostic-support-for-Test-ML-script.patch
recipes-test/tegra-tests/nvidia-docker-tests/0002-Add-version-remap-script-support.patch
recipes-test/tegra-tests/nvidia-docker-tests/l4t_version_remap.sh.in
recipes-test/tegra-tests/nvidia-docker-tests_1.0.bb

Remove workaround to use Jetpack 5 tags now that Jetpack 5.1 containers are released for r35.2.1
Go to latest master on jetson-containers

nvidia-docker-tests: upstream 5.1 updates

---

recipes-devtools/deepstream/deepstream-6.2_6.2.0-1.bb

This update to fix issue [#259](https://github.com/OE4T/tegra-demo-distro/issues/259)

deepstream-6.2: update work around for gRPC and protobuf

---

recipes-connectivity/openssl/openssl111_1.1.1u.bb

Update openSSL 1.1.1l to 1.1.1u to patch the following CVEs : CVE-2022-1292, CVE-2022-2068, CVE-2022-0778, CVE-2022-4450, CVE-2023-0215, CVE-2023-0464, CVE-2023-0286, CVE-2021-4160, CVE-2022-4304, CVE-2022-2097, CVE-2023-0465, CVE-2023-0466.

Kirkstone l4t r32.7.x - update openSSL to patch CVEs.

---

recipes-connectivity/openssh/openssh_%.bbappend

Per the commit message for 868dfb46d96a27ec9041cb902fb769330277257d in OE-Core, kernel support random numbers changed in v5.6 and later, and the RRECOMMENDS we were modifying no longer exists in the recipe.

openssh: remove bbappend

---

recipes-devtools/triton/triton-backend_2.22.0.bb
recipes-devtools/triton/triton-client/0001-Build-fixups.patch
recipes-devtools/triton/triton-client_2.22.0.bb
recipes-devtools/triton/triton-core_2.22.0.bb
recipes-devtools/triton/triton-python-backend_2.22.0.bb
recipes-devtools/triton/triton-server_2.22.0.bb
recipes-devtools/triton/triton-tensorrt-backend/0001-Build-fixups.patch
recipes-devtools/triton/triton-tensorrt-backend/0002-add-support-for-kUINT8.patch
recipes-devtools/triton/triton-tensorrt-backend_2.22.0.bb

* This PR is dedicated to fix the issue #79 
* Tests were done on `jetson-agx-xavier-devkit` with image `demo-image-full`
* Add the following line in your `conf/local.conf`
```
CORE_IMAGE_BASE_INSTALL:append = " triton-client triton-core triton-server"
```
* Running `tritonserver` application 
```
root@jetson-agx-orin-devkit:~# /usr/bin/tritonserver --model-repository=./triton_model_repo --backend-directory=/usr/lib --backend-config=tensorrt,version=8.4.1 --min-supported-compute-capability=5.3 --http-address=0.0.0.0 --http-port=8000
I1127 22:41:41.037633 884 pinned_memory_manager.cc:240] Pinned memory pool is created at '0x203b8e000' with size 268435456
I1127 22:41:41.038173 884 cuda_memory_manager.cc:105] CUDA memory pool is created on device 0 with size 67108864
I1127 22:41:41.046317 …
```

triton: update recipes

---

recipes-devtools/deepstream/deepstream-6.3-pyds/0001-Fixes-for-cross-building.patch
recipes-devtools/deepstream/deepstream-6.3-pyds/0002-Allow-apps-to-be-run-from-other-working-directories.patch
recipes-devtools/deepstream/deepstream-6.3-pyds_1.1.8.bb
recipes-devtools/deepstream/deepstream-6.3_6.3.0-1.bb
recipes-test/tegra-tests/deepstream-tests/run-deepstream-tests.sh
recipes-test/tegra-tests/deepstream-tests_1.0.bb

* Tests were done by using `demo-image-full` image on `Jetson AGX Orin` devkit
*  add the following line into your `conf/local.conf`
```
CORE_IMAGE_BASE_INSTALL:append = " deepstream-tests deepstream-6.3 deepstream-6.3-pyds"
```
* Run `run-deepstream-tests` script
```
nvstreammux: Successfully handled EOS for source_id=0
Frame Number= 1438 Number of Objects= 16 Vehicle_count= 13 Person_count= 3
Frame Number= 1438 Number of Objects= 15 Vehicle_count= 12 Person_count= 3
Frame Number= 1439 Number of Objects= 14 Vehicle_count= 11 Person_count= 3
Frame Number= 1439 Number of Objects= 14 Vehicle_count= 11 Person_count= 3
Frame Number= 1440 Number of Objects= 13 Vehicle_count= 11 Person_count= 2
Frame Number= 1440 Number of Objects= 15 Vehicle_count= 12 Person_count= 3
nvstreammux: Successfully …
```

Updates for deepstream 6.3

---

recipes-test/tegra-tests/nvidia-docker-tests/l4t_version_remap.sh.in

I've noticed the repo at https://github.com/dusty-nv/jetson-containers has undergone a major overhaul recently.  We'll need to pull in some [python dependencies](https://github.com/dusty-nv/jetson-containers/blob/master/requirements.txt) and possibly other things to use it.  Haven't tried to take that on at the moment, will patch the work off the legacy branch for now instead.

nvidia-docker-tests: update remap for version 35.x

---

recipes-devtools/deepstream/deepstream-6.3-pyds/0001-Fixes-for-cross-building.patch
recipes-devtools/deepstream/deepstream-6.3_6.3.0-1.bb

* Leave the deepstream headers under `/opt/deepstream`, rather than double-installing them into `${includedir}`
* Update the deepstream-pyds recipe to find the headers in the correct deepstream-specific location
Fixes [meta-tegra #1401](https://github.com/OE4T/meta-tegra/issues/1401)

deepstream: fix header file collisions

---

recipes-devtools/deepstream/deepstream-6.3_6.3.0-1.bb

* Update the DT_NEEDED rewrites for grpc and protobuf to use the actual SONAMEs for the libraries, rather than hard-coding
* Restore ${PN}-staticdev to the PACKAGES setting to provide a home for the lone static library in the SDK.
Fixes #102

deepstream-6.3: fix packaging issues

---

recipes-support/re2/re2_2020.11.01.bb

RE2 renamed the master branch in main.
This is only relevant for `Dunfell` since RE2 is part of `meta-oe` since `Kirkstone`.

re2: set branch to main

---

recipes-test/tegra-tests/tensorrt-tests/run-tensorrt-tests.sh

mnist.prototxt were removed in JetPack 6.0 / L4T R36.2.0 DP
* Tests were done on machine `jetson-agx-orin-devkit` with `demo-image-full` image.
```
[02/27/2024-18:35:51] [I] Average on 10 runs - GPU latency: 4.78064 ms - Host latency: 4.83948 ms (enqueue 0.356567 ms)
[02/27/2024-18:35:51] [I] Average on 10 runs - GPU latency: 4.77766 ms - Host latency: 4.83599 ms (enqueue 0.356763 ms)
[02/27/2024-18:35:51] [I] Average on 10 runs - GPU latency: 4.7771 ms - Host latency: 4.83513 ms (enqueue 0.363037 ms)
[02/27/2024-18:35:51] [I] Average on 10 runs - GPU latency: 4.77773 ms - Host latency: 4.8364 ms (enqueue 0.363794 ms)
[02/27/2024-18:35:51] [I] 
[02/27/2024-18:35:51] [I] === Performance summary ===
[02/27/2024-18:35:51] [I] Throughput: 208.729 qps
[02/27/2024-18:35:51] [I] Latency: min = …
```

Update TensorRT test script

---

recipes-devtools/deepstream/deepstream-6.3_6.3.0-1.bb

* Added 'nmos' PACKAGECONFIG setting for enabling/disabling inclusion of NMOS (Network Media Open Specification) support, which requires avahi to be built with libdns_sd in its PACKAGECONFIG.
* Added dependency for the 'azure' PACKAGECONFIG setting on azure-iot-sdk
This is a backport of https://github.com/OE4T/meta-tegra-community/commit/79dea834cd0a04c7fd6399f8394905d759e707ce to deepstream 6.3
Resolves build error:
```
Running transaction check
Transaction check succeeded.
Running transaction test
Error: Transaction test error:
file /usr/lib/libnss_mdns.so.2 conflicts between attempted installs of libnss-mdns-0.15.1-r0.armv8a_tegra and mdns-2200.100.94.0.2-r0.armv8a_tegra
```

deepstream-6.3: PACKAGECONFIG updates

---

recipes-devtools/python/python3-cuda/0001-OE-cross-build-fixups.patch

OE-core/master has QA diagnostics about it and some distros e.g. yoe turn that into an Error
Fixes
ERROR: python3-cuda-12.2.1-r0 do_patch: QA Issue: Missing Upstream-Status in patch

python3-cuda: Add missing upstream status to patch

---

recipes-devtools/python/python3-cuda_12.2.1.bb

- Add to CXXFLAGS as it uses g++ not gcc
- Avoid using '=' for implicit sysroot expansion which works with gcc but may not work with all compilers

python3-cuda: Switch build backend to PEP-517

---

recipes-test/tegra-tests/nvidia-docker-tests/l4t_version_remap.sh.in

Add remap to the latest supported version of all containers to ensure run-docker-tests passes on r35.6.0

nvidia-docker-tests: support r35.6.0

---

recipes-devtools/cnmem/cnmem/0001-cmake-Set-minimum-required-version-to-3.5-for-CMake-.patch
recipes-devtools/cnmem/cnmem_v1.0.0.bb
recipes-devtools/dlpack/dlpack/0002-cmake-Set-minimum-required-version-to-3.5-for-CMake-.patch
recipes-devtools/dlpack/dlpack_1.0.bb
recipes-devtools/libevhtp/libevhtp/0001-fix-cmake-build.patch
recipes-devtools/libevhtp/libevhtp/0002-cmake-Set-minimum-required-version-to-3.5-for-CMake-.patch
recipes-devtools/libevhtp/libevhtp_1.2.18.bb
recipes-devtools/pytorch/pytorch/0007-cmake-Set-minimum-required-version-to-3.5-for-CMake-.patch
recipes-devtools/pytorch/pytorch_2.5.0.bb
recipes-devtools/triton/triton-common/0002-cmake-Set-minimum-required-version-to-3.5-for-CMake-.patch
recipes-devtools/triton/triton-common_2.58.0.bb
recipes-support/nsync/nsync/0002-cmake-Set-minimum-required-version-to-3.5-for-CMake-.patch
recipes-support/nsync/nsync_1.26.0.bb
recipes-support/safeint/safeint/0002-cmake-Set-minimum-required-version-to-3.5-for-CMake-.patch
recipes-support/safeint/safeint_3.0.28.bb
recipes-support/yaml-cpp/yaml-cpp-070/0002-cmake-Set-minimum-required-version-to-3.5-for-CMake-.patch
recipes-support/yaml-cpp/yaml-cpp-070_0.7.0.bb

Those commits fixes the following issue:
```
| CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
|   Compatibility with CMake < 3.5 has been removed from CMake.
|
|   Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
|   to tell CMake that the project requires at least <min> but has been updated
|   to work with policies introduced by <max> or earlier.
|
|   Or, add -DCMAKE_POLICY_VERSION_MINIMUM=3.5 to try configuring anyway.
|
|
| -- Configuring incomplete, errors occurred!
```

Fix CMake 4+ compatibility

---

recipes-devtools/pytorch/pytorch_2.5.0.bb

When building this recipe, it errored out because it was using python3 from `/usr/bin` on my machine which was too out of date.
With this change, it will now properly use the yocto provided host python, which in my case is a new enough version that the build can now succeed.

pytorch: use python3-native instead of host python
